# We use gpt-3.5-turbo-1106 because it doesn't work, so we can test that the
# the specification for the modules (below) actually works. gpt-3.5-turbo-0301, gpt-4
default_llm:
  id: gpt-3.5-turbo-1106
  temperature: 0.0
languages: English, Spanish

modules:
  - name: call_appointment
    llm:
      id: gpt-4
      temperature: 0.0
  - name: top-level
    llm:
      id:  gpt-4
      temperature: 0.0
  - name: photo_qa
    llm:
      id:  gpt-4
      temperature: 0.0
  - name: session_details
    llm:  gpt-4
  - name: estimate_price
    llm:  gpt-4