name: Python test using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v3
      with:
          environment-file: environment.yml
          python-version: 3.9
          activate-environment: test
    - name: Show conda information
      shell: bash -l {0}
      run: |
          conda info
          conda list        
#    - name: Lint with flake8
#      shell: bash -l {0}
#      run: |
#        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
#        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        pytest tests/
